import type { Preset } from './types'
import { DEFAULT_ENGINE_PARAMS } from '../audio/EngineParams'

export const BUILT_IN_PRESETS: readonly Preset[] = [
  {
    id:          'default',
    name:        'Default',
    description: 'Balanced starting point',
    params:      { ...DEFAULT_ENGINE_PARAMS },
  },
  {
    id:          'slap',
    name:        'Slap',
    description: 'Punchy and percussive with a bright click',
    params: {
      attack:          0.05,
      sustain:         false,
      releaseTime:     60,
      retrigger:       true,
      portamento:      false,
      portamentoTime:  100,
      tone:        0.65,
      dampFreq:    220,
      dampAmount:  0.4,
      eqLow:       4,
      eqMid:       2,
      eqHigh:      1,
      drive:       0.15,
      volume:      0.8,
    },
  },
  {
    id:          'jazz-upright',
    name:        'Jazz Upright',
    description: 'Warm, thumpy, old-school acoustic feel',
    params: {
      attack:          0.75,
      sustain:         false,
      releaseTime:     60,
      retrigger:       false,
      portamento:      false,
      portamentoTime:  100,
      tone:        0.1,
      dampFreq:    70,
      dampAmount:  0.9,
      eqLow:       5,
      eqMid:       -3,
      eqHigh:      -8,
      drive:       0,
      volume:      0.8,
    },
  },
  {
    id:          'rock',
    name:        'Rock',
    description: 'Midrange grind with light overdrive',
    params: {
      attack:          0.3,
      sustain:         false,
      releaseTime:     120,
      retrigger:       true,
      portamento:      false,
      portamentoTime:  100,
      tone:        0.45,
      dampFreq:    150,
      dampAmount:  0.55,
      eqLow:       3,
      eqMid:       3,
      eqHigh:      0,
      drive:       0.35,
      volume:      0.8,
    },
  },
  {
    id:          'fretless',
    name:        'Fretless',
    description: 'Smooth and singing with long natural decay and pitch slides',
    params: {
      attack:          0.85,
      sustain:         true,
      releaseTime:     400,
      retrigger:       false,
      portamento:      true,
      portamentoTime:  180,
      tone:        0.35,
      dampFreq:    120,
      dampAmount:  0.45,
      eqLow:       2,
      eqMid:       1,
      eqHigh:      -2,
      drive:       0.05,
      volume:      0.8,
    },
  },
]
